-- Active: 1780491452595@@127.0.0.1@5432@customer_behaviour@public--
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public';
SELECT column_name FROM information_schema.columns 
WHERE table_name = 'customer';
set SEARCH_PATH TO public;


SELECT * FROM customer LIMIT 20;

--Q1. What is the total revenue generated by male vs. femalecustomers?
select gender ,SUM(purchase_amount) as revenue from customer
group by gender
--Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount 
FROM customer
WHERE discount_applied = 'YES'
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);
--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating)::numeric,2) AS avg_rating 
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_pct
FROM customer
GROUP BY item_purchased
ORDER BY discount_pct DESC
LIMIT 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT customer_id, previous_purchases,
       CASE
           WHEN previous_purchases = 0 THEN 'New'
           WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
           ELSE 'Loyal'
       END AS customer_segment
FROM customer
ORDER BY previous_purchases DESC;
--Q8. What are the top 3 most purchased products within each category?
SELECT * FROM (
    SELECT category, item_purchased,
           COUNT(*) AS purchase_count,
           RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank
    FROM customer
    GROUP BY category, item_purchased
) ranked
WHERE rank <= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    CASE WHEN previous_purchases > 5 THEN 'Repeat Buyer' ELSE 'Non-Repeat' END AS buyer_type,
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY 
        CASE WHEN previous_purchases > 5 THEN 'Repeat Buyer' ELSE 'Non-Repeat' END), 2) AS percentage
FROM customer
GROUP BY buyer_type, subscription_status
ORDER BY buyer_type;
--Q10. What is the revenue contribution of each age group?                                                           
SELECT age_group,
       SUM(purchase_amount) AS total_revenue,
       ROUND(100.0 * SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM customer), 2) AS revenue_pct
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;